### ISSUE TITLE
webpack 打包压缩的时候失败

### ISSUE THREAD

**Issue by linjieAda** [woodemi/notepad-core-js#51]
`
ERROR in minifying js/0.c194adcd.js
SyntaxError: Unexpected token: name (EventEmitter)
`

当我引用`import * as NotepadCore from 'notepad-core`的时候
cross-env NODE_ENV=test webpack -p --mode production 报了上面的错误
cross-env NODE_ENV=dev node webpack-dev-server.js --mode development 没有报错

"webpack": "^4.20.2",
"webpack-cli": "^3.1.2",
"webpack-dev-server": "^3.1.9",

node 8.15.0

**Comment by Sunbreak** [comment]
notepad-core依赖Web Bluetooth，比较新的技术，所以没有做ES 2015 -> ES 5的转换，可能是语法太新了，所以Webpack打包失败

建议先运行example/web吧，还有其他问题可以加微信woodemi

**Comment by linjieAda** [comment]
把你们src下的代码放到本地，不通过npm安装，webpack打包是好的
